language: node_js
node_js:
- '0.12'
- '4.2'
- '6.9'
script:
- npm run build && npm test
sudo: false
after_success:
  cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
  email: false
  slack:
    secure: EOZZJJboKX+qGE7nuAL2t0kbe0LDkmMLJ56oyDb6nOuaPTZ+YLrzXq+6H3OnPCDNH3qHna+dyG6AxsR7EbuBR/6bFUk4NE6Bq13iegZHlIdVsX0ZUmRMbhaRm8xbreU8NltFNN6xi/QN+zpNkHn8UmoX2sR+78OcDim7ACdbSLs=
